//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class Student
    {
        //[DataMember(Order = 0)]
        public int id { get; set; }

        //[DataMember(Order = 1)]
        public string name { get; set; }

        //[DataMember(Order = 2)]
        public int age { get; set; }
    }
}
