//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    /// <summary>
    /// A class representing student
    /// </summary>
    public partial class Student
    {
        /// <summary>
        /// id is a primary key
        /// </summary>
        //[DataMember(Order = 0)]
        public int id { get; set; }

        /// <summary>
        /// name is users full name
        /// </summary>
        //[DataMember(Order = 1)]
        public string name { get; set; }


        /// <summary>
        /// age is int value
        /// </summary>
        //[DataMember(Order = 2)]
        public int age { get; set; }
    }
}
